import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { z } from "zod";
import { contentService } from "@/services/content-service";
import { ArticleCard } from "@/components/gamepulse/cards";
import { EmptyState, LoadingSkeleton } from "@/components/states/states";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
export const Route=createFileRoute("/search")({validateSearch:(s)=>z.object({q:z.string().optional()}).parse(s),head:()=>({meta:[{title:"Search Gaming Stories — GAMEPULSE"},{name:"description",content:"Search GAMEPULSE news, reviews, guides and games."},{property:"og:title",content:"Search — GAMEPULSE"},{property:"og:description",content:"Search GAMEPULSE news, reviews, guides and games."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/search"}]}),component:SearchPage});
function SearchPage(){const {q}=Route.useSearch();const [input,setInput]=useState(q??"");const [query,setQuery]=useState(q??"");const [loading,setLoading]=useState(false);const results=contentService.searchArticles(query);useEffect(()=>{setInput(q??"");setQuery(q??"")},[q]);const run=(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setTimeout(()=>{setQuery(input);setLoading(false)},250)};return <main className="container-page py-12 sm:py-20"><p className="eyebrow">Discover</p><h1 className="display-title mt-2 text-6xl sm:text-8xl">Search</h1><form onSubmit={run} className="mt-8 flex max-w-3xl gap-2"><label htmlFor="site-search" className="sr-only">Search games, news, reviews and guides</label><Input id="site-search" value={input} onChange={e=>setInput(e.target.value)} className="h-12" placeholder="Search games, news, reviews and guides..."/><Button size="icon" className="size-12" aria-label="Search"><Search/></Button></form>{!query&&!loading?<div className="mt-12"><p className="eyebrow">Popular searches</p><div className="mt-4 flex flex-wrap gap-2">{["Project Velocity","FPS settings","Co-op games","Esports"].map(x=><Link key={x} to="/search" search={{q:x}} className="rounded-sm border border-border px-4 py-2 text-sm hover:border-primary">{x}</Link>)}</div></div>:loading?<div className="mt-12"><LoadingSkeleton/></div>:results.length?<section className="mt-12"><p className="mb-7 text-sm text-muted-foreground">{results.length} result{results.length===1?"":"s"} for “{query}”</p><div className="grid gap-7">{results.map(a=><ArticleCard key={a.id} article={a} layout="horizontal"/>)}</div></section>:<EmptyState/>}</main>}
