import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, ChevronRight } from "lucide-react";
import type { CategorySlug } from "@/data/types";
import { contentService } from "@/services/content-service";
import { ArticleCard, Meta, SectionHeading, articlePath } from "@/components/gamepulse/cards";
import { Button } from "@/components/ui/button";
export function Breadcrumbs({items}:{items:{label:string;to?:string}[]}){return <nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><Link to="/" className="hover:text-foreground">Home</Link>{items.map(i=><span key={i.label} className="flex items-center gap-2"><ChevronRight className="size-3"/>{i.to?<Link to={i.to as "/news"}>{i.label}</Link>:<span>{i.label}</span>}</span>)}</nav>}
export function CategoryPage({slug}:{slug:CategorySlug}){const category=contentService.getCategory(slug);const articles=contentService.getArticlesByCategory(slug);const [count,setCount]=useState(5);const featured=articles.find(a=>a.featured)??articles[0];if(!category||!featured)return null;return <main><section className="border-b border-border bg-surface"><div className="container-page py-12 sm:py-20"><Breadcrumbs items={[{label:category.name}]}/><p className="eyebrow mt-10">Explore</p><h1 className="display-title mt-2 text-6xl sm:text-8xl">{category.name}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-muted-foreground">{category.description}</p></div></section><div className="container-page py-12"><Link to={articlePath(featured)} className="group relative block min-h-[28rem] overflow-hidden rounded-md"><img src={featured.image} alt="" width={1400} height={900} className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]"/><div className="story-overlay absolute inset-0"/><div className="absolute inset-x-0 bottom-0 max-w-3xl p-6 sm:p-10"><p className="eyebrow">Featured story</p><h2 className="mt-3 text-4xl font-bold text-primary-foreground sm:text-6xl">{featured.title}</h2><p className="mt-4 max-w-xl text-sm leading-6 text-primary-foreground/80">{featured.excerpt}</p><div className="mt-5 text-primary-foreground"><Meta article={featured}/></div></div></Link><div className="mt-16 grid gap-12 lg:grid-cols-[minmax(0,1fr)_20rem]"><section><SectionHeading title="Latest stories"/><div className="grid gap-7">{articles.slice(0,count).map(a=><ArticleCard key={a.id} article={a} layout="horizontal"/>)}</div>{count<articles.length&&<Button variant="outline" onClick={()=>setCount(c=>c+4)} className="mt-8">Load more <ArrowRight/></Button>}</section><aside><div className="sticky top-28"><SectionHeading title="Popular"/>{contentService.getTrendingArticles().slice(0,4).map(a=><div key={a.id} className="border-b border-border py-4"><ArticleCard article={a} layout="compact"/></div>)}<div className="mt-8 overflow-hidden"><p className="eyebrow mb-3">Trending now</p><div className="flex flex-wrap gap-2">{["GTA 6","Steam","PlayStation","Xbox","Nintendo","Valorant"].map(t=><span key={t} className="rounded-sm bg-muted px-3 py-2 text-xs">{t}</span>)}</div></div></div></aside></div></div></main>}
