import { useState } from "react";
import { Check, Gamepad2, Mail, ShieldCheck, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { brand } from "@/config/brand";
const values=[{Icon:Gamepad2,title:"Players first",copy:"We explain what each story means for the people who play."},{Icon:ShieldCheck,title:"Clear standards",copy:"Mock content is labeled by context and never presented as verified breaking news."},{Icon:Users,title:"A broader culture",copy:"Games connect technology, art, sport and communities around the world."}];
export function AboutPage(){return <main><section className="surface-grid border-b border-border bg-surface"><div className="container-page py-20"><p className="eyebrow">Independent by design</p><h1 className="display-title mt-3 max-w-5xl text-6xl sm:text-9xl">We follow the signal, not the noise.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{brand.name} is a fictional editorial publication prototype built around useful reporting, honest criticism and deep enthusiasm for games.</p></div></section><section className="container-page grid gap-12 py-16 md:grid-cols-3">{values.map(({Icon,title,copy})=><article key={title} className="border-t-2 border-primary pt-6"><Icon className="size-7 text-primary"/><h2 className="mt-5 text-3xl font-bold">{title}</h2><p className="mt-3 leading-7 text-muted-foreground">{copy}</p></article>)}</section></main>}
export function ContactPage(){const [done,setDone]=useState(false);const submit=(e:React.FormEvent)=>{e.preventDefault();setDone(true)};return <main className="container-page py-16"><p className="eyebrow">Contact the desk</p><h1 className="display-title mt-3 text-7xl sm:text-9xl">Let&apos;s talk games.</h1><div className="mt-12 grid gap-12 lg:grid-cols-[.7fr_1fr]"><div><Mail className="size-8 text-primary"/><h2 className="mt-5 text-3xl font-bold">News tips, feedback and partnerships</h2><p className="mt-4 leading-7 text-muted-foreground">This prototype form works locally and does not send or store your message yet.</p></div>{done?<div role="status" className="grid min-h-72 place-items-center rounded-md border border-border bg-surface"><div className="text-center"><Check className="mx-auto size-10 text-accent"/><h2 className="mt-4 text-3xl font-bold">Message ready</h2><p className="mt-2 text-muted-foreground">Thanks — the local demonstration is complete.</p></div></div>:<form onSubmit={submit} className="grid gap-5 rounded-md border border-border bg-card p-6"><Field id="name" label="Name"/><Field id="email" label="Email" type="email"/><div><label htmlFor="message" className="mb-2 block text-sm font-bold">Message</label><Textarea id="message" required rows={6}/></div><Button type="submit" className="justify-self-start">Send message</Button></form>}</div></main>}
function Field({id,label,type="text"}:{id:string;label:string;type?:string}){return <div><label htmlFor={id} className="mb-2 block text-sm font-bold">{label}</label><Input id={id} type={type} required/></div>}
export function LegalPage({title,type}:{title:string;type:"privacy"|"terms"|"disclaimer"}){const sections=type==="privacy"?[["Information and privacy","This frontend demonstration does not collect, transmit or store personal information."],["Future services","Before analytics, accounts or newsletter delivery launch, this notice must be replaced with final service-specific terms."],["Your choices","Future controls for consent, access and deletion will be documented here."]]:type==="terms"?[["Using GAMEPULSE","These placeholder terms describe the intended structure of the future publication."],["Editorial material","Content is provided for information and entertainment. Rights and reuse terms will be finalized before launch."],["Changes","Final terms may change when the production service and its features are established."]]:[["Editorial disclosure","GAMEPULSE currently uses fictional mock stories and authors for frontend demonstration."],["Affiliate disclosure","Product cards are ready for future affiliate links, but no affiliate tracking or commercial URLs are active."],["Not professional advice","Gaming, hardware and purchasing coverage is general editorial information, not legal, financial or professional advice."]];return <main className="container-page py-16"><p className="eyebrow">Legal placeholder</p><h1 className="display-title mt-3 text-6xl sm:text-8xl">{title}</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Last updated September 23, 2026. This structured placeholder requires legal review before a production launch.</p><div className="mt-12 max-w-3xl divide-y divide-border border-y border-border">{sections.map(([h,p])=><section key={h} className="py-8"><h2 className="text-3xl font-bold">{h}</h2><p className="mt-4 leading-8 text-muted-foreground">{p}</p></section>)}</div></main>}
export function NotFoundPage(){return <main className="surface-grid grid min-h-[70vh] place-items-center px-4 text-center"><div><p className="eyebrow">Error 404</p><h1 className="display-title mt-3 text-7xl sm:text-9xl">You&apos;ve left the map.</h1><p className="mx-auto mt-5 max-w-lg text-muted-foreground">The page you&apos;re looking for doesn&apos;t exist or the mission has moved.</p><Button asChild className="mt-7"><a href="/">Return home</a></Button></div></main>}
