import { Link, useRouterState } from "@tanstack/react-router";
import { Menu, Moon, Search, Sun, Youtube, Instagram, MessageCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { brand } from "@/config/brand";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Sheet, SheetClose, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { Input } from "@/components/ui/input";
import { NewsletterCTA } from "@/components/gamepulse/newsletter";
const nav=[{to:"/",label:"Home"},{to:"/news",label:"News"},{to:"/reviews",label:"Reviews"},{to:"/guides",label:"Guides"},{to:"/pc-gaming",label:"PC"},{to:"/mobile-gaming",label:"Mobile"},{to:"/esports",label:"Esports"}] as const;
const allNav=[...nav,{to:"/about",label:"About"},{to:"/contact",label:"Contact"}] as const;
function Logo(){return <Link to="/" aria-label={`${brand.name} home`} className="flex shrink-0 items-center gap-2 font-display text-2xl font-black"><span className="grid size-8 place-items-center rounded-sm bg-primary text-xs text-primary-foreground">{brand.mark}</span><span>{brand.name}</span></Link>}
function SearchDialog(){const [q,setQ]=useState("");return <Dialog><DialogTrigger asChild><Button size="icon" variant="ghost" aria-label="Search"><Search/></Button></DialogTrigger><DialogContent className="top-[20%] max-w-xl translate-y-0 bg-popover"><DialogHeader><DialogTitle className="text-3xl font-display uppercase">Search GAMEPULSE</DialogTitle><DialogDescription>Find news, reviews, guides and games.</DialogDescription></DialogHeader><form className="mt-3" onSubmit={e=>{e.preventDefault();if(q.trim())window.location.href=`/search?q=${encodeURIComponent(q)}`}}><div className="flex gap-2"><Input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search games, news, reviews and guides..."/><Button type="submit" size="icon" aria-label="Submit search"><Search/></Button></div></form><div className="mt-2"><p className="eyebrow">Popular searches</p><div className="mt-3 flex flex-wrap gap-2">{["Project Velocity","FPS settings","Co-op games","Esports"].map(x=><Link key={x} to="/search" search={{q:x}} className="rounded-sm border border-border px-3 py-2 text-xs hover:border-primary">{x}</Link>)}</div></div></DialogContent></Dialog>}
export function Header(){const [dark,setDark]=useState(true);const [scrolled,setScrolled]=useState(false);const path=useRouterState({select:s=>s.location.pathname});useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]);useEffect(()=>{const onScroll=()=>setScrolled(scrollY>24);onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>removeEventListener("scroll",onScroll)},[]);return <header className={`sticky top-0 z-40 border-b transition-all ${scrolled?"border-border bg-background/95 shadow-lg backdrop-blur":"border-transparent bg-background/75 backdrop-blur-md"}`}><div className="container-page grid h-16 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 lg:h-20 lg:grid-cols-[auto_minmax(0,1fr)_auto]"><Logo/><nav aria-label="Main navigation" className="hidden justify-center lg:flex">{nav.map(item=><Link key={item.to} to={item.to} activeOptions={{exact:item.to==="/"}} className={`relative px-3 py-7 text-sm font-bold transition-colors hover:text-foreground ${path===item.to||path.startsWith(`${item.to}/`)?"text-foreground after:absolute after:inset-x-3 after:bottom-0 after:h-0.5 after:bg-primary":"text-muted-foreground"}`}>{item.label}</Link>)}</nav><div className="flex shrink-0 items-center"><SearchDialog/><Button size="icon" variant="ghost" onClick={()=>setDark(v=>!v)} aria-label={dark?"Switch to light theme":"Switch to dark theme"}>{dark?<Sun/>:<Moon/>}</Button><Sheet><SheetTrigger asChild><Button size="icon" variant="ghost" className="lg:hidden" aria-label="Open menu"><Menu/></Button></SheetTrigger><SheetContent className="w-[88vw] bg-background"><SheetHeader><SheetTitle><Logo/></SheetTitle></SheetHeader><nav className="mt-10 grid" aria-label="Mobile navigation">{allNav.map(item=><SheetClose asChild key={item.to}><Link to={item.to} className="border-b border-border py-4 font-display text-2xl font-bold uppercase hover:text-primary">{item.label}</Link></SheetClose>)}</nav></SheetContent></Sheet></div></div></header>}
const socials=[{Icon:Youtube,label:"YouTube"},{Icon:Instagram,label:"Instagram"},{Icon:MessageCircle,label:"Discord"}];
export function Footer(){return <footer className="mt-24 border-t border-border bg-surface"><div className="container-page py-16"><div className="grid gap-12 lg:grid-cols-[1.2fr_2fr]"><div><Logo/><p className="mt-5 max-w-sm leading-7 text-muted-foreground">{brand.description}</p><div className="mt-6 flex gap-2">{socials.map(({Icon,label})=><Button key={label} size="icon" variant="outline" aria-label={label}><Icon/></Button>)}</div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-4"><FooterGroup title="Explore" links={nav.slice(0,6)}/><FooterGroup title="Company" links={[{to:"/about",label:"About"},{to:"/contact",label:"Contact"}]}/><FooterGroup title="Legal" links={[{to:"/privacy-policy",label:"Privacy"},{to:"/terms",label:"Terms"},{to:"/disclaimer",label:"Disclaimer"}]}/><div><p className="eyebrow mb-4">Follow</p><p className="text-sm leading-7 text-muted-foreground">YouTube<br/>Instagram<br/>X<br/>Discord</p></div></div></div><div className="mt-14"><NewsletterCTA compact/></div><div className="mt-10 border-t border-border pt-6 text-xs text-muted-foreground">© 2026 {brand.name}. Mock editorial content for frontend demonstration.</div></div></footer>}
type StaticRoute="/"|"/news"|"/reviews"|"/guides"|"/pc-gaming"|"/mobile-gaming"|"/esports"|"/about"|"/contact"|"/privacy-policy"|"/terms"|"/disclaimer";
function FooterGroup({title,links}:{title:string;links:readonly {to:StaticRoute;label:string}[]}){return <div><p className="eyebrow mb-4">{title}</p><div className="grid gap-3">{links.map(l=><Link key={l.to} to={l.to} className="text-sm text-muted-foreground hover:text-foreground">{l.label}</Link>)}</div></div>}
