/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EsportsRouteImport } from './routes/esports'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as MobileGamingRouteImport } from './routes/mobile-gaming'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PcGamingRouteImport } from './routes/pc-gaming'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EsportsSlugRouteImport } from './routes/esports.$slug'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as MobileGamingSlugRouteImport } from './routes/mobile-gaming.$slug'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as PcGamingSlugRouteImport } from './routes/pc-gaming.$slug'
import { Route as ReviewsSlugRouteImport } from './routes/reviews.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsRoute = EsportsRouteImport.update({
  id: '/esports',
  path: '/esports',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileGamingRoute = MobileGamingRouteImport.update({
  id: '/mobile-gaming',
  path: '/mobile-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PcGamingRoute = PcGamingRouteImport.update({
  id: '/pc-gaming',
  path: '/pc-gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EsportsSlugRoute = EsportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EsportsRoute,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const MobileGamingSlugRoute = MobileGamingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MobileGamingRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const PcGamingSlugRoute = PcGamingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PcGamingRoute,
} as any)
const ReviewsSlugRoute = ReviewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReviewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/esports': typeof EsportsRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/mobile-gaming': typeof MobileGamingRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/pc-gaming': typeof PcGamingRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/search': typeof SearchRoute
  '/esports/$slug': typeof EsportsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mobile-gaming/$slug': typeof MobileGamingSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pc-gaming/$slug': typeof PcGamingSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/esports': typeof EsportsRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/mobile-gaming': typeof MobileGamingRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/pc-gaming': typeof PcGamingRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/search': typeof SearchRoute
  '/esports/$slug': typeof EsportsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mobile-gaming/$slug': typeof MobileGamingSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pc-gaming/$slug': typeof PcGamingSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/esports': typeof EsportsRouteWithChildren
  '/guides': typeof GuidesRouteWithChildren
  '/mobile-gaming': typeof MobileGamingRouteWithChildren
  '/news': typeof NewsRouteWithChildren
  '/pc-gaming': typeof PcGamingRouteWithChildren
  '/reviews': typeof ReviewsRouteWithChildren
  '/search': typeof SearchRoute
  '/esports/$slug': typeof EsportsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/mobile-gaming/$slug': typeof MobileGamingSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/pc-gaming/$slug': typeof PcGamingSlugRoute
  '/reviews/$slug': typeof ReviewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/esports'
    | '/guides'
    | '/mobile-gaming'
    | '/news'
    | '/pc-gaming'
    | '/reviews'
    | '/search'
    | '/esports/$slug'
    | '/games/$slug'
    | '/guides/$slug'
    | '/mobile-gaming/$slug'
    | '/news/$slug'
    | '/pc-gaming/$slug'
    | '/reviews/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/esports'
    | '/guides'
    | '/mobile-gaming'
    | '/news'
    | '/pc-gaming'
    | '/reviews'
    | '/search'
    | '/esports/$slug'
    | '/games/$slug'
    | '/guides/$slug'
    | '/mobile-gaming/$slug'
    | '/news/$slug'
    | '/pc-gaming/$slug'
    | '/reviews/$slug'
  id:
    | '__root__'
    | '/'
    | '/esports'
    | '/guides'
    | '/mobile-gaming'
    | '/news'
    | '/pc-gaming'
    | '/reviews'
    | '/search'
    | '/esports/$slug'
    | '/games/$slug'
    | '/guides/$slug'
    | '/mobile-gaming/$slug'
    | '/news/$slug'
    | '/pc-gaming/$slug'
    | '/reviews/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EsportsRoute: typeof EsportsRouteWithChildren
  GuidesRoute: typeof GuidesRouteWithChildren
  MobileGamingRoute: typeof MobileGamingRouteWithChildren
  NewsRoute: typeof NewsRouteWithChildren
  PcGamingRoute: typeof PcGamingRouteWithChildren
  ReviewsRoute: typeof ReviewsRouteWithChildren
  SearchRoute: typeof SearchRoute
  GamesSlugRoute: typeof GamesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports': {
      id: '/esports'
      path: '/esports'
      fullPath: '/esports'
      preLoaderRoute: typeof EsportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-gaming': {
      id: '/mobile-gaming'
      path: '/mobile-gaming'
      fullPath: '/mobile-gaming'
      preLoaderRoute: typeof MobileGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pc-gaming': {
      id: '/pc-gaming'
      path: '/pc-gaming'
      fullPath: '/pc-gaming'
      preLoaderRoute: typeof PcGamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esports/$slug': {
      id: '/esports/$slug'
      path: '/$slug'
      fullPath: '/esports/$slug'
      preLoaderRoute: typeof EsportsSlugRouteImport
      parentRoute: typeof EsportsRoute
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/mobile-gaming/$slug': {
      id: '/mobile-gaming/$slug'
      path: '/$slug'
      fullPath: '/mobile-gaming/$slug'
      preLoaderRoute: typeof MobileGamingSlugRouteImport
      parentRoute: typeof MobileGamingRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/pc-gaming/$slug': {
      id: '/pc-gaming/$slug'
      path: '/$slug'
      fullPath: '/pc-gaming/$slug'
      preLoaderRoute: typeof PcGamingSlugRouteImport
      parentRoute: typeof PcGamingRoute
    }
    '/reviews/$slug': {
      id: '/reviews/$slug'
      path: '/$slug'
      fullPath: '/reviews/$slug'
      preLoaderRoute: typeof ReviewsSlugRouteImport
      parentRoute: typeof ReviewsRoute
    }
  }
}

interface EsportsRouteChildren {
  EsportsSlugRoute: typeof EsportsSlugRoute
}

const EsportsRouteChildren: EsportsRouteChildren = {
  EsportsSlugRoute: EsportsSlugRoute,
}

const EsportsRouteWithChildren =
  EsportsRoute._addFileChildren(EsportsRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface MobileGamingRouteChildren {
  MobileGamingSlugRoute: typeof MobileGamingSlugRoute
}

const MobileGamingRouteChildren: MobileGamingRouteChildren = {
  MobileGamingSlugRoute: MobileGamingSlugRoute,
}

const MobileGamingRouteWithChildren = MobileGamingRoute._addFileChildren(
  MobileGamingRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PcGamingRouteChildren {
  PcGamingSlugRoute: typeof PcGamingSlugRoute
}

const PcGamingRouteChildren: PcGamingRouteChildren = {
  PcGamingSlugRoute: PcGamingSlugRoute,
}

const PcGamingRouteWithChildren = PcGamingRoute._addFileChildren(
  PcGamingRouteChildren,
)

interface ReviewsRouteChildren {
  ReviewsSlugRoute: typeof ReviewsSlugRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsSlugRoute: ReviewsSlugRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EsportsRoute: EsportsRouteWithChildren,
  GuidesRoute: GuidesRouteWithChildren,
  MobileGamingRoute: MobileGamingRouteWithChildren,
  NewsRoute: NewsRouteWithChildren,
  PcGamingRoute: PcGamingRouteWithChildren,
  ReviewsRoute: ReviewsRouteWithChildren,
  SearchRoute: SearchRoute,
  GamesSlugRoute: GamesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
